name: Manual Workflow
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'The release tag for the assets'
        required: true
        default: 'rolling/2025-09-05'
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release_tag }}"
